### ISSUE TITLE
Database scheme missing

### ISSUE THREAD

**Issue by rteunissen** [donatmarko/ivao-tracker-backend#2]
In the ivao tracker backend, the scheme for the mysql database is missing. In the files it doesn't get created anywhere. Is this somewhere available?

**Comment by donatmarko** [comment]
Hello,
It does indeed missing, I'm gonna add it asap. 
Thanks,

**Comment by donatmarko** [comment]
Issue has been addressed in commit b9b2c91.
https://github.com/donatmarko/ivao-tracker-backend/commit/b9b2c914513cb20b99a07c855098665576e859bf
